

MAKEFILE	= Makefile.mingw
COPY	= copy /y

SUBTARGETS	= \
	sub-BoostSignals \
	sub-OpenGLSample1 \
	sub-SmartSOAPGoogleAPITester \
	sub-SmartSOAPWsdlParser \
	sub-SmartSOAPWsdlParserTester \
	sub-WidgetChildWindow \
	sub-AddressBook \
	sub-Calculator \
	sub-Canvas \
	sub-CustomWidget \
	sub-FreeDialogTester \
	sub-HelloSmartWin \
	sub-HelloSmartWinWorld \
	sub-NotePad \
	sub-Threads \
	sub-TicTacToe \
	sub-TimerTest \
	sub-WidgetButton \
	sub-WidgetButtonTriggerHappy \
	sub-WidgetCheckBox \
	sub-WidgetComboBox \
	sub-WidgetDateTimePicker \
	sub-WidgetFun \
	sub-WidgetInherited \
	sub-WidgetList \
	sub-WidgetLoadFile \
	sub-WidgetMDIWindow \
	sub-WidgetMenu \
	sub-WidgetMessageBox \
	sub-WidgetModalDialog \
	sub-WidgetProgressBar \
	sub-WidgetRadioButtonGroup \
	sub-WidgetRichTextBox \
	sub-WidgetSaveFile \
	sub-WidgetSlider \
	sub-WidgetSpinner \
	sub-WidgetSplitter \
	sub-WidgetStatic \
	sub-WidgetStatusBar \
	sub-WidgetTabControl \
	sub-WidgetTextBox \
	sub-WidgetToolbar \
	sub-WidgetTreeView \
	sub-WidgetWindow \
	sub-WidgetWindowSubclassed \
	sub-iolib \
	sub-sw_mdi \
	sub-SampleWidgets 
	
CLEANSUBTARGETS	= \
	clean-sub-BoostSignals \
	clean-sub-OpenGLSample1 \
	clean-sub-SmartSOAPGoogleAPITester \
	clean-sub-SmartSOAPWsdlParser \
	clean-sub-SmartSOAPWsdlParserTester \
	clean-sub-WidgetChildWindow \
	clean-sub-AddressBook \
	clean-sub-Calculator \
	clean-sub-Canvas \
	clean-sub-CustomWidget \
	clean-sub-FreeDialogTester \
	clean-sub-HelloSmartWin \
	clean-sub-HelloSmartWinWorld \
	clean-sub-NotePad \
	clean-sub-Threads \
	clean-sub-TicTacToe \
	clean-sub-TimerTest \
	clean-sub-WidgetButton \
	clean-sub-WidgetButtonTriggerHappy \
	clean-sub-WidgetCheckBox \
	clean-sub-WidgetComboBox \
	clean-sub-WidgetDateTimePicker \
	clean-sub-WidgetFun \
	clean-sub-WidgetInherited \
	clean-sub-WidgetList \
	clean-sub-WidgetLoadFile \
	clean-sub-WidgetMDIWindow \
	clean-sub-WidgetMenu \
	clean-sub-WidgetMessageBox \
	clean-sub-WidgetModalDialog \
	clean-sub-WidgetProgressBar \
	clean-sub-WidgetRadioButtonGroup \
	clean-sub-WidgetRichTextBox \
	clean-sub-WidgetSaveFile \
	clean-sub-WidgetSlider \
	clean-sub-WidgetSpinner \
	clean-sub-WidgetSplitter \
	clean-sub-WidgetStatic \
	clean-sub-WidgetStatusBar \
	clean-sub-WidgetTabControl \
	clean-sub-WidgetTextBox \
	clean-sub-WidgetToolbar \
	clean-sub-WidgetTreeView \
	clean-sub-WidgetWindow \
	clean-sub-WidgetWindowSubclassed \
	clean-sub-iolib \
	clean-sub-sw_mdi \
	clean-sub-SampleWidgets 
	
	
all: $(SUBTARGETS)
clean: $(CLEANSUBTARGETS)


sub-AddressBook	: FORCE
	cd AddressBook	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-BoostSignals : FORCE
	cd BoostSignals	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-Calculator	: FORCE
	cd Calculator	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-Canvas	: FORCE
	cd Canvas	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-CustomWidget	: FORCE
	cd CustomWidget	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-FreeDialogTester: FORCE
	cd FreeDialogTester	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-HelloSmartWin	: FORCE
	cd HelloSmartWin	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-HelloSmartWinWorld	: FORCE
	cd HelloSmartWinWorld	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-NotePad	: FORCE
	cd NotePad	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-OpenGLSample1	: FORCE
	cd OpenGLSample1	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
	
sub-SmartSOAPGoogleAPITester : FORCE
	cd SmartSOAPGoogleAPITester 	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-SmartSOAPWsdlParser : FORCE
	cd SmartSOAPWsdlParser	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-SmartSOAPWsdlParserTester : FORCE
	cd SmartSOAPWsdlParserTester	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
		
sub-Threads	: FORCE
	cd Threads	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-TicTacToe	: FORCE
	cd TicTacToe	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-TimerTest	: FORCE
	cd TimerTest	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetButton	: FORCE
	cd WidgetButton	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetButtonTriggerHappy	: FORCE
	cd WidgetButtonTriggerHappy	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetChildWindow : FORCE
	cd WidgetChildWindow	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-WidgetCheckBox	: FORCE
	cd WidgetCheckBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetComboBox	: FORCE
	cd WidgetComboBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetDateTimePicker	: FORCE
	cd WidgetDateTimePicker	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetFun	: FORCE
	cd WidgetFun	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetInherited	: FORCE
	cd WidgetInherited	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetList	: FORCE
	cd WidgetList	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetLoadFile	: FORCE
	cd WidgetLoadFile	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetMDIWindow	: FORCE
	cd WidgetMDIWindow	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetMenu	: FORCE
	cd WidgetMenu	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetMessageBox	: FORCE
	cd WidgetMessageBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetModalDialog	: FORCE
	cd WidgetModalDialog	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetProgressBar	: FORCE
	cd WidgetProgressBar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetRadioButtonGroup	: FORCE
	cd WidgetRadioButtonGroup	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetRichTextBox	: FORCE
	cd WidgetRichTextBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetSaveFile	: FORCE
	cd WidgetSaveFile	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetSlider	: FORCE
	cd WidgetSlider	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetSpinner	: FORCE
	cd WidgetSpinner	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetSplitter	: FORCE
	cd WidgetSplitter	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetStatic	: FORCE
	cd WidgetStatic	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetStatusBar	: FORCE
	cd WidgetStatusBar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetTabControl	: FORCE
	cd WidgetTabControl	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetTextBox	: FORCE
	cd WidgetTextBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetToolbar	: FORCE
	cd WidgetToolbar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetTreeView	: FORCE
	cd WidgetTreeView	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetWindow	: FORCE
	cd WidgetWindow	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-WidgetWindowSubclassed	: FORCE
	cd WidgetWindowSubclassed	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-iolib	: FORCE
	cd iolib	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..

sub-sw_mdi	: FORCE
	cd sw_mdi	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE)
	@cd ..
	
sub-SampleWidgets	: FORCE
	cd PocketPC\SmartWinDevicesUnitTests\SampleWidgets	&& \
	$(MAKE) -f $(MAKEFILE)
	@cd ..\..\..


###################################################

clean-sub-BoostSignals	: FORCE
	cd BoostSignals	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
		
clean-sub-OpenGLSample1	: FORCE
	cd OpenGLSample1	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-SmartSOAPGoogleAPITester	: FORCE
	cd SmartSOAPGoogleAPITester	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-SmartSOAPWsdlParser	: FORCE
	cd SmartSOAPWsdlParser	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-SmartSOAPWsdlParserTester	: FORCE
	cd SmartSOAPWsdlParserTester	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-WidgetChildWindow	: FORCE
	cd WidgetChildWindow	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-AddressBook	: FORCE
	cd AddressBook	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-Calculator	: FORCE
	cd Calculator	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-Canvas	: FORCE
	cd Canvas	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-CustomWidget	: FORCE
	cd CustomWidget	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-FreeDialogTester	: FORCE
	cd FreeDialogTester	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-HelloSmartWin	: FORCE
	cd HelloSmartWin	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-HelloSmartWinWorld	: FORCE
	cd HelloSmartWinWorld	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-sw_mdi	: FORCE
	cd sw_mdi	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-NotePad	: FORCE
	cd NotePad	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-Threads	: FORCE
	cd Threads	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-TicTacToe	: FORCE
	cd TicTacToe	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-TimerTest	: FORCE
	cd TimerTest	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetButton	: FORCE
	cd WidgetButton	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetButtonTriggerHappy	: FORCE
	cd WidgetButtonTriggerHappy	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetCheckBox	: FORCE
	cd WidgetCheckBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetComboBox	: FORCE
	cd WidgetComboBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetDateTimePicker	: FORCE
	cd WidgetDateTimePicker	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetFun	: FORCE
	cd WidgetFun	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetInherited	: FORCE
	cd WidgetInherited	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetList	: FORCE
	cd WidgetList	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetLoadFile	: FORCE
	cd WidgetLoadFile	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetMDIWindow	: FORCE
	cd WidgetMDIWindow	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetMenu	: FORCE
	cd WidgetMenu	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetMessageBox	: FORCE
	cd WidgetMessageBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetModalDialog	: FORCE
	cd WidgetModalDialog	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetProgressBar	: FORCE
	cd WidgetProgressBar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetRadioButtonGroup	: FORCE
	cd WidgetRadioButtonGroup	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetRichTextBox	: FORCE
	cd WidgetRichTextBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetSaveFile	: FORCE
	cd WidgetSaveFile	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetSlider	: FORCE
	cd WidgetSlider	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetSpinner	: FORCE
	cd WidgetSpinner	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetSplitter	: FORCE
	cd WidgetSplitter	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetStatic	: FORCE
	cd WidgetStatic	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetStatusBar	: FORCE
	cd WidgetStatusBar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetTabControl	: FORCE
	cd WidgetTabControl	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetTextBox	: FORCE
	cd WidgetTextBox	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetToolbar	: FORCE
	cd WidgetToolbar	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetTreeView	: FORCE
	cd WidgetTreeView	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetWindow	: FORCE
	cd WidgetWindow	&& \
	$(COPY) ..\$(MAKEFILE).4all $(MAKEFILE)  && \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-WidgetWindowSubclassed	: FORCE
	cd WidgetWindowSubclassed	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sub-iolib	: FORCE
	cd iolib	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..

clean-sw_mdi	: FORCE
	cd sw_mdi	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..
	
clean-sub-SampleWidgets	: FORCE
	cd PocketPC\SmartWinDevicesUnitTests\SampleWidgets	&& \
	$(MAKE) -f $(MAKEFILE) clean
	@cd ..\..\..







install:  install_subdirs

uninstall:  uninstall_subdirs



FORCE:

