RC =  WidgetList
OBJ = Main.o $(RC).o

		
BIN = main-mingw.exe
CXXFLAGS = -W0 -O2
CPPFLAGS = -I../../include -DNDEBUG
LDFLAGS = -L../../lib
LDLIBS = -lsmartwin -lsmartsoap -lcomctl32 -luser32 -lGdi32 -lopengl32 -lglu32 -lkernel32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -limm32 -lwinmm -lwsock32 -lwinspool -lcomdlg32
	
$(BIN): $(OBJ) 
	$(CXX) $(LDFLAGS) -o "$(BIN)" $(OBJ)  $(LDLIBS)

$(RC).o: 
	windres -i $(RC).rc -o $(RC).o --include-dir=.

.PHONY:  clean

clean:
	rm -f $(OBJ)
	rm -f $(BIN)