BIN = main-mingw.exe
SRC = Main.cpp 
OBJ = $(SRC:.cpp=.o)
#CXXFLAGS = -frtti -fexceptions -I../../include -DNDEBUG -Wall -Wold-style-cast -Wsign-compare -Wconversion -Wpointer-arith -pedantic -O2
CXXFLAGS = -W0 -frtti -fexceptions -O2 -I../../include -DNDEBUG
LIBPATH = -L../../lib
LIBS = -lsmartwin -lsmartsoap -lcomctl32 -luser32 -lGdi32 -lopengl32 -lglu32 -lkernel32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -limm32 -lwinmm -lwsock32 -lwinspool -lcomdlg32 -lws2_32 -lwininet

.PHONY: build clean

build:	$(BIN)

clean:
	$(RM) $(BIN)
	$(RM) $(OBJ)

$(BIN): $(OBJ)
	$(CXX) $(LDFLAGS) $(LIBPATH) -o $@ $^ $(LDLIBS) $(LIBS)
	
